"""Handcrafted demo emails — ported verbatim from TypeScript demo-emails.ts."""

from __future__ import annotations

from invoice_agent.types import RawEmail

DEMO_EMAILS: list[RawEmail] = [
    RawEmail(
        id='demo-1',
        thread_id='demo-thread-1',
        subject='Invoice #INV-1042 from Northwind Supplies',
        from_='billing@northwind.example <billing@northwind.example>',
        date='Fri, 10 Jul 2026 09:14:00 +0000',
        snippet='Please find attached invoice INV-1042 for £1,240.50 due 31 July 2026.',
        body_text='\nHello,\n\nPlease find invoice INV-1042 for office supplies.\n\nTotal Amount Due: £1,240.50\nPayment Due Date: 31 July 2026\nInvoice Number: INV-1042\n\nKind regards,\nNorthwind Supplies Billing\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-2',
        thread_id='demo-thread-2',
        subject='Your AWS Invoice is available',
        from_='Amazon Web Services <no-reply@amazon.com>',
        date='Mon, 06 Jul 2026 12:00:00 +0000',
        snippet='Your payment of $312.88 will be charged on July 20, 2026.',
        body_text='\nAmazon Web Services\nInvoice Summary\n\nAccount: demo-account\nAmount due: $312.88 USD\nDue date: July 20, 2026\nInvoice ID: 123456789\n\nThank you for your business.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-3',
        thread_id='demo-thread-3',
        subject='Team lunch next Friday?',
        from_='alex@company.example',
        date='Wed, 08 Jul 2026 15:22:00 +0000',
        snippet='Want to grab lunch with the team next Friday?',
        body_text='Want to grab lunch with the team next Friday? No rush either way.',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-4',
        thread_id='demo-thread-4',
        subject='Receipt for your Figma subscription',
        from_='Figma <receipts@figma.com>',
        date='Tue, 01 Jul 2026 08:00:00 +0000',
        snippet='You paid $45.00 for Figma Professional.',
        body_text='\nReceipt\n\nFigma Professional — Monthly\nAmount paid: $45.00\nDate paid: July 1, 2026\nThank you for your payment.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-5',
        thread_id='demo-thread-5',
        subject='Invoice 7781 — Cloudhost Ltd',
        from_='accounts@cloudhost.example',
        date='Thu, 02 Jul 2026 11:45:00 +0000',
        snippet='Invoice 7781 for EUR 890.00 due within 14 days.',
        body_text='\nCloudhost Ltd\n\nINVOICE 7781\nBill To: Demo Co\n\nSubtotal: EUR 890.00\nVAT: EUR 0.00\nTotal: EUR 890.00\n\nDue Date: 16/07/2026\nPlease pay by bank transfer.\n',
        attachment_texts=[
            'INVOICE 7781\nTotal Due: EUR 890.00\nPayment due by 16/07/2026\n',
        ],
    ),
    RawEmail(
        id='demo-6',
        thread_id='demo-thread-6',
        subject='Invoice from Stripe — INV-28419',
        from_='Stripe Billing <invoices@stripe.com>',
        date='Sun, 05 Jul 2026 16:30:00 +0000',
        snippet='Invoice INV-28419 for $1,499.00 due August 1, 2026.',
        body_text='\nStripe, Inc.\n\nTAX INVOICE\nInvoice number: INV-28419\nBill to: Ledgerline Demo\n\nAmount due: $1,499.00 USD\nDue date: August 1, 2026\n\nPay online or by ACH.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-7',
        thread_id='demo-thread-7',
        subject='Your Adobe Creative Cloud receipt',
        from_='Adobe <noreply@adobe.com>',
        date='Sat, 04 Jul 2026 07:12:00 +0000',
        snippet='Payment received: $59.99',
        body_text='\nAdobe Receipt\n\nCreative Cloud All Apps\nAmount charged: $59.99\nPayment date: July 4, 2026\nStatus: Paid in full\n\nThis is not a bill. No further action needed.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-8',
        thread_id='demo-thread-8',
        subject='Birthday dinner plans?',
        from_='sam@friends.example',
        date='Fri, 03 Jul 2026 19:05:00 +0000',
        snippet='Are you free for dinner on the 25th?',
        body_text='\nHey!\n\nAre you free for birthday dinner on the 25th? Thinking Italian.\n\nNo invoices here — just life.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-9',
        thread_id='demo-thread-9',
        subject='Spotify for Business — Invoice SP-9021',
        from_='Spotify Billing <billing@spotify.com>',
        date='Thu, 09 Jul 2026 10:00:00 +0000',
        snippet='Invoice SP-9021 — €240.00 due 23 July 2026',
        body_text='\nSpotify for Business\n\nINVOICE SP-9021\nPlan: Premium Team (10 seats)\n\nTotal amount due: €240.00\nPayment due date: 23 July 2026\n\nPlease settle by the due date to avoid service interruption.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-10',
        thread_id='demo-thread-10',
        subject='This week in product: changelog digest',
        from_='Product Weekly <digest@newsletter.example>',
        date='Mon, 13 Jul 2026 06:00:00 +0000',
        snippet='Five launches worth knowing about',
        body_text='\nProduct Weekly\n\n1. Dark mode polish\n2. Faster exports\n3. New shortcuts\n\nUnsubscribe anytime. This is a marketing newsletter, not a bill.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-11',
        thread_id='demo-thread-11',
        subject='Legal services invoice — Harcourt & Co',
        from_='accounts@harcourt-legal.example',
        date='Tue, 07 Jul 2026 14:18:00 +0000',
        snippet='Invoice HC-441 for £3,200.00 — see attached PDF.',
        body_text='\nDear Client,\n\nPlease find our invoice for June legal services attached.\n\nRegards,\nHarcourt & Co Accounts\n',
        attachment_texts=[
            '\nHARCOURT & CO\nTAX INVOICE HC-441\n\nProfessional services — June 2026\nAmount due: £3,200.00 GBP\nDue date: 28 July 2026\nBank transfer preferred.\n',
        ],
    ),
    RawEmail(
        id='demo-12',
        thread_id='demo-thread-12',
        subject='Your Uber trip receipt',
        from_='Uber Receipts <receipts@uber.com>',
        date='Wed, 15 Jul 2026 22:41:00 +0000',
        snippet='You paid $18.40 for your trip.',
        body_text='\nUber Receipt\n\nTrip completed\nTotal charged: $18.40\nPaid with Visa •••• 4242\nDate: July 15, 2026\n\nThis receipt confirms payment already taken.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-13',
        thread_id='demo-thread-13',
        subject='Slack invoice ready — SI-77820',
        from_='Slack Billing <billing@slack.com>',
        date='Fri, 17 Jul 2026 11:05:00 +0000',
        snippet='Your Slack invoice SI-77820 is $860.00 due Aug 5, 2026.',
        body_text='\nSlack Technologies\n\nInvoice SI-77820\nWorkspace: ledgerline-demo\n\nBalance due: USD 860.00\nDue date: August 5, 2026\n\nPlease remit payment by the due date.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-14',
        thread_id='demo-thread-14',
        subject='Your package has shipped',
        from_='ShopFast Shipping <ship@shopfast.example>',
        date='Sat, 11 Jul 2026 13:33:00 +0000',
        snippet='Tracking number SF-991122',
        body_text='\nGood news — your order shipped.\n\nTracking: SF-991122\nEstimated delivery: July 14, 2026\n\nNo payment is due. This is a shipping notice only.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-15',
        thread_id='demo-thread-15',
        subject='Freelance design invoice — FD-318',
        from_='Maya Chen <maya@studio.example>',
        date='Mon, 14 Jul 2026 09:40:00 +0000',
        snippet='Invoice FD-318 for €1,750.00 due 30 July 2026',
        body_text='\nHi team,\n\nInvoice for brand refresh work:\n\nInvoice #: FD-318\nTotal due: EUR 1,750.00\nDue: 30 July 2026\n\nWire details in the signature.\nThanks,\nMaya\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-16',
        thread_id='demo-thread-16',
        subject='GitHub invoice #GH-55201',
        from_='GitHub Billing <billing@github.com>',
        date='Sun, 12 Jul 2026 08:20:00 +0000',
        snippet='Invoice GH-55201 — $210.00 due July 26, 2026',
        body_text='\nGitHub, Inc.\n\nINVOICE GH-55201\nOrganization: ledgerline-demo\n\nAmount due: $210.00 USD\nPayment due by: July 26, 2026\n\nThank you for using GitHub.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-17',
        thread_id='demo-thread-17',
        subject='Coffee catch-up tomorrow?',
        from_='jordan@company.example',
        date='Tue, 14 Jul 2026 17:55:00 +0000',
        snippet='Free at 10am for a quick coffee?',
        body_text='Free at 10am tomorrow for a quick coffee? No agenda — just catch up.',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-18',
        thread_id='demo-thread-18',
        subject='Payment confirmation — Northern Power',
        from_='Northern Power <receipts@northernpower.example>',
        date='Thu, 16 Jul 2026 07:48:00 +0000',
        snippet='We received your payment of £86.12',
        body_text='\nNorthern Power — Payment Receipt\n\nAccount: 44002119\nAmount paid: £86.12\nPayment date: 16 July 2026\nStatus: Settled\n\nThank you. This confirms a completed payment; nothing further is owed.\n',
        attachment_texts=[],
    ),
    RawEmail(
        id='demo-19',
        thread_id='demo-thread-19',
        subject='Consulting invoice attached — Apex Advisory',
        from_='billing@apex-advisory.example',
        date='Wed, 08 Jul 2026 12:10:00 +0000',
        snippet='Please see attached invoice AA-909 for $4,500.00.',
        body_text='\nHello,\n\nAttached is our consulting invoice for Q2 strategy work.\n\nPlease arrange payment by the due date on the PDF.\n\n— Apex Advisory Billing\n',
        attachment_texts=[
            '\nAPEX ADVISORY LLC\nINVOICE AA-909\n\nConsulting services — Q2 2026\nTotal amount due: $4,500.00 USD\nDue date: August 12, 2026\nNet 30 terms.\n',
        ],
    ),
    RawEmail(
        id='demo-20',
        thread_id='demo-thread-20',
        subject='Weekend hiking photos',
        from_='chris@personal.example',
        date='Sun, 05 Jul 2026 20:15:00 +0000',
        snippet='Here are a few shots from the trail.',
        body_text='\nAttached (not really) some hiking photos from the weekend.\n\nHope you had a good one — talk soon!\n',
        attachment_texts=[],
    ),
]

if len(DEMO_EMAILS) != 20:
    raise RuntimeError(
        f"DEMO_EMAILS must contain exactly 20 emails, found {len(DEMO_EMAILS)}"
    )
